### PR TITLE
Laravel 5 compatibility

### PR DESCRIPTION
**Pull request by sboo**
I updated the base classes to be compatible with Laravel 5.
However, the Guard dependency injection in __construct (see for example Middleware\Authenticate) doesn't work yet.

For that, the Serviceprovider needs to register this singleton correctly:

```
$this->app->singleton('auth.driver', function($app)
{
    return $app['auth']->driver();
});
```

### CODE REVIEW

**Comment by ldynia** [comment]
Hi Ramon how you resolved problem of "BindingResolutionException in Container.php line 785: Target [Illuminate\Contracts\Auth\UserProvider] is not instantiable." It appears in the constructor of the Guard class (first parameter) [ __construct(UserProvider $provider...)]?

**Comment by sboo** [comment]
@ldynia check my post here
https://laracasts.com/discuss/channels/general-discussion/multiple-authentication-in-laravel-5-ldap-and-default-auth?page=1#reply-44260

you can use the Auth Facase instead of the Guard injection, that works for now. I haven't had time to look at it in depth yet.

**Comment by ldynia** [comment]
@sboo I have promble installing your fork. Could you provide me the line of code for composer installation ? I tried this but indicates that repository doesn't exist. Thanks :)
~~~php
	"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sboo/multiauth"
        }
    ],
	"require": {
		"sboo/multiauth" : "master",
~~~

**Comment by sboo** [comment]
The package is still called ""ollieread/multiauth". 

Add this instead:
"ollieread/multiauth" : "dev-master"

I would advise you not to use this in a production right now, or only with caution. I will work on it shorty and fix a few more things

**Comment by ldynia** [comment]
Thanks and it sounds awesome. I will watch it then :)

**Comment by sboo** [comment]
To use my fork for now, add the following:

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sboo/multiauth"
        }
    ],
    "require": {
        "ollieread/multiauth" : "dev-master"
   }
```

This is compatible with L5

**Comment by ldynia** [comment]
Thanks! Finally I can install it :) I will play with it, and I will update you If I will find something suspicious. Cheers!

**Comment by ollieread** [comment]
Does this actually provide all of the same functionality that the 4.1 uses and that the default 5 Auth does?

**Comment by sboo** [comment]
There is no functional difference with your version at all, I just made it 5.0 compatible. Even 5.1, except that the default auth traits can't be used.

**Comment by ollieread** [comment]
Did you create replacement traits?

**Comment by sboo** [comment]
Will do.  I haven't had time to create the traits yet, I was away until just a few days ago. Will try and do it this week.

**Pull request closed without merging**
